if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv", lib="/usr/local/lib/R/site-library");
renv::activate()
renv::restore()

library('methods', warn.conflicts = FALSE, character.only = TRUE)
library('tidyverse', warn.conflicts = FALSE, character.only = TRUE)
library('ggthemes', warn.conflicts = FALSE, character.only = TRUE)
library('gridExtra', warn.conflicts = FALSE, character.only = TRUE)
library('zoo', warn.conflicts = FALSE, character.only = TRUE)
library('dplyr', warn.conflicts = FALSE, character.only = TRUE)
library('lubridate', warn.conflicts = FALSE, character.only = TRUE)
library('xtable', warn.conflicts = FALSE, character.only = TRUE)
library('expint', warn.conflicts = FALSE, character.only = TRUE)
library('deSolve', warn.conflicts = FALSE, character.only = TRUE)
library('qrcode', warn.conflicts = FALSE, character.only = TRUE)
library('ggplotify', warn.conflicts = FALSE, character.only = TRUE)
library('gtools', warn.conflicts = FALSE, character.only = TRUE)
