# Automatically updates the lock file for the seed environment to have the latest versions
name: Update Renv

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # midnight every saturday
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stephenc/docker-science-data-reporting:main
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Update
        run: |
          cd seed-environments/r
          Rscript update.R
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          BRANCH_NAME: 'main'          